# Generated by Django 4.2.8 on 2024-01-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_brandmodel_alter_productmodel_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='descrption',
            new_name='description',
        ),
    ]
