# Generated by Django 4.2.8 on 2024-01-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_descrption_productmodel_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='newPrice',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='oldPrice',
            new_name='old_price',
        ),
    ]
