# Generated by Django 4.2.8 on 2024-01-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_newprice_productmodel_new_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='image_url',
        ),
    ]
