# Generated by Django 4.2.8 on 2024-01-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0007_ordermodel_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandModel',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='CategoryModel',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='OrderModel',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderItemsModel',
            new_name='OrderItems',
        ),
        migrations.RenameModel(
            old_name='ProductModel',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ReviewModel',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='ShippingAddressModel',
            new_name='ShippingAddress',
        ),
        migrations.RenameModel(
            old_name='UserModel',
            new_name='User',
        ),
    ]
