# Generated by Django 4.2.8 on 2024-01-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_user_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
