# Generated by Django 4.2.8 on 2024-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_order_created_alter_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slod_count',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
