# Generated by Django 4.2.8 on 2024-01-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_slod_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slod_count',
            new_name='sold_count',
        ),
    ]
