# Generated by Django 4.2.8 on 2024-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0024_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
