# Generated by Django 4.2.8 on 2024-01-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_usermodel_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='group',
        ),
    ]
