# Generated by Django 4.2.8 on 2024-01-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_usermodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(default='/avatar.svg', null=True, upload_to=''),
        ),
    ]
