# Generated by Django 4.2.8 on 2024-01-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_usermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='city',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(blank=True, default='Unknown', max_length=200, null=True),
        ),
    ]
