# Generated by Django 4.2.8 on 2024-01-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_usermodel_city_alter_usermodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, default='+000 000-000-000', max_length=200, null=True),
        ),
    ]
