# Generated by Django 4.2.8 on 2024-01-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_usermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='/placeholder.jpg', upload_to=''),
        ),
    ]
